
package com.bps.sw.pgw.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PaymentGatewayImplService", targetNamespace = "http://service.pgw.sw.bps.com/", wsdlLocation = "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl")
public class PaymentGatewayImplService
    extends Service
{

    private final static URL PAYMENTGATEWAYIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bps.sw.pgw.service.PaymentGatewayImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.bps.sw.pgw.service.PaymentGatewayImplService.class.getResource(".");
            url = new URL(baseUrl, "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAYMENTGATEWAYIMPLSERVICE_WSDL_LOCATION = url;
    }

    public PaymentGatewayImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentGatewayImplService() {
        super(PAYMENTGATEWAYIMPLSERVICE_WSDL_LOCATION, new QName("http://service.pgw.sw.bps.com/", "PaymentGatewayImplService"));
    }

    /**
     * 
     * @return
     *     returns IPaymentGateway
     */
    @WebEndpoint(name = "PaymentGatewayImplPort")
    public IPaymentGateway getPaymentGatewayImplPort() {
        return super.getPort(new QName("http://service.pgw.sw.bps.com/", "PaymentGatewayImplPort"), IPaymentGateway.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPaymentGateway
     */
    @WebEndpoint(name = "PaymentGatewayImplPort")
    public IPaymentGateway getPaymentGatewayImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.pgw.sw.bps.com/", "PaymentGatewayImplPort"), IPaymentGateway.class, features);
    }

}
